version: '2'
services:

  postgres:
    image: postgres:9.5.2
    env_file: ./docker/directory-sso/.env-postgres.test

  directory_sso_webserver:
    image: ukti/directory-sso:latest
    depends_on: [postgres]
    links: [postgres]
    container_name: sso.trade.great.docker
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://postgres:5432 -timeout 60s
    command: ./docker/cmd-integration-test-webserver.sh
    ports: ["8003:8003"]
    env_file: ./docker/directory-sso/.env.test

  sut:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [directory_sso_webserver]
    links: [directory_sso_webserver]
    ports: ["8004:8004"]
    working_dir: /usr/src/app
    entrypoint: dockerize -wait http://sso.trade.great.docker:8003/api/v1/healthcheck/database/?token=debug -timeout 120s
    command: ./docker/cmd-test.sh
    env_file: ./docker/.env.test
    restart: "no"
