[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.circleci
    | \.github
    | \.pytest_cache
    | \.venv
    | \.vscode
    | venv
  )/
  | manage.py       # also separately exclude a file in the root of the project
)
'''
